### ISSUE TITLE
error on using NSGA2 algorithm

### ISSUE THREAD

**Issue by jermaine1ronquillo** [andresgciamtez/ppno#2]
Running example 6 and 7 with nsga-2 algorithm would result an AttributeError

**Comment by andresgciamtez** [comment]
Sorry I was quite busy. I corrected it.

**Comment by jermaine1ronquillo** [comment]
There are no errors running example 6 and 7, however there is no result produced (no *.inp file)

**Comment by andresgciamtez** [comment]
Are you absolutely sure?
Example6.ext must generate: BIN_Solved_NSGA2.inp

**Comment by jermaine1ronquillo** [comment]
Yes there is no BIN_Solved_NSGA2.inp file generated

**Comment by andresgciamtez** [comment]
In my PC it is generated properly. Please, could you try it again?
